//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.AdamResurces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Country {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Country() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.AdamResurces._Country", typeof(_Country).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزيرة أسينشيون.
        /// </summary>
        public static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أندورا.
        /// </summary>
        public static string AD {
            get {
                return ResourceManager.GetString("AD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإمارات العربية المتحدة.
        /// </summary>
        public static string AE {
            get {
                return ResourceManager.GetString("AE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفغانستان.
        /// </summary>
        public static string AF {
            get {
                return ResourceManager.GetString("AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنتيغوا وبربودا.
        /// </summary>
        public static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنغويلا.
        /// </summary>
        public static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألبانيا.
        /// </summary>
        public static string AL {
            get {
                return ResourceManager.GetString("AL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرمينيا.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنغولا.
        /// </summary>
        public static string AO {
            get {
                return ResourceManager.GetString("AO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنتاركتيكا.
        /// </summary>
        public static string AQ {
            get {
                return ResourceManager.GetString("AQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأرجنتين.
        /// </summary>
        public static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساموا الأمريكية.
        /// </summary>
        public static string AS {
            get {
                return ResourceManager.GetString("AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النمسا.
        /// </summary>
        public static string AT {
            get {
                return ResourceManager.GetString("AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أستراليا.
        /// </summary>
        public static string AU {
            get {
                return ResourceManager.GetString("AU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آروبا.
        /// </summary>
        public static string AW {
            get {
                return ResourceManager.GetString("AW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر آلاند.
        /// </summary>
        public static string AX {
            get {
                return ResourceManager.GetString("AX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أذربيجان.
        /// </summary>
        public static string AZ {
            get {
                return ResourceManager.GetString("AZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوسنة والهرسك.
        /// </summary>
        public static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بربادوس.
        /// </summary>
        public static string BB {
            get {
                return ResourceManager.GetString("BB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنجلاديش.
        /// </summary>
        public static string BD {
            get {
                return ResourceManager.GetString("BD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلجيكا.
        /// </summary>
        public static string BE {
            get {
                return ResourceManager.GetString("BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوركينا فاسو.
        /// </summary>
        public static string BF {
            get {
                return ResourceManager.GetString("BF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلغاريا.
        /// </summary>
        public static string BG {
            get {
                return ResourceManager.GetString("BG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البحرين.
        /// </summary>
        public static string BH {
            get {
                return ResourceManager.GetString("BH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوروندي.
        /// </summary>
        public static string BI {
            get {
                return ResourceManager.GetString("BI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنين.
        /// </summary>
        public static string BJ {
            get {
                return ResourceManager.GetString("BJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سان بارتليمي.
        /// </summary>
        public static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برمودا.
        /// </summary>
        public static string BM {
            get {
                return ResourceManager.GetString("BM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروناي.
        /// </summary>
        public static string BN {
            get {
                return ResourceManager.GetString("BN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوليفيا.
        /// </summary>
        public static string BO {
            get {
                return ResourceManager.GetString("BO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هولندا الكاريبية.
        /// </summary>
        public static string BQ {
            get {
                return ResourceManager.GetString("BQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرازيل.
        /// </summary>
        public static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباهاما.
        /// </summary>
        public static string BS {
            get {
                return ResourceManager.GetString("BS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوتان.
        /// </summary>
        public static string BT {
            get {
                return ResourceManager.GetString("BT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتسوانا.
        /// </summary>
        public static string BW {
            get {
                return ResourceManager.GetString("BW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روسيا البيضاء.
        /// </summary>
        public static string BY {
            get {
                return ResourceManager.GetString("BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بليز.
        /// </summary>
        public static string BZ {
            get {
                return ResourceManager.GetString("BZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كندا.
        /// </summary>
        public static string CA {
            get {
                return ResourceManager.GetString("CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر كوكوس.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكونغو - كينشاسا.
        /// </summary>
        public static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمهورية أفريقيا الوسطى.
        /// </summary>
        public static string CF {
            get {
                return ResourceManager.GetString("CF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكونغو - برازافيل.
        /// </summary>
        public static string CG {
            get {
                return ResourceManager.GetString("CG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سويسرا.
        /// </summary>
        public static string CH {
            get {
                return ResourceManager.GetString("CH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساحل العاج.
        /// </summary>
        public static string CI {
            get {
                return ResourceManager.GetString("CI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر كوك.
        /// </summary>
        public static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شيلي.
        /// </summary>
        public static string CL {
            get {
                return ResourceManager.GetString("CL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاميرون.
        /// </summary>
        public static string CM {
            get {
                return ResourceManager.GetString("CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصين.
        /// </summary>
        public static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كولومبيا.
        /// </summary>
        public static string CO {
            get {
                return ResourceManager.GetString("CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوستاريكا.
        /// </summary>
        public static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوبا.
        /// </summary>
        public static string CU {
            get {
                return ResourceManager.GetString("CU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرأس الأخضر.
        /// </summary>
        public static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوراساو.
        /// </summary>
        public static string CW {
            get {
                return ResourceManager.GetString("CW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزيرة الكريسماس.
        /// </summary>
        public static string CX {
            get {
                return ResourceManager.GetString("CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبرص.
        /// </summary>
        public static string CY {
            get {
                return ResourceManager.GetString("CY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمهورية التشيك.
        /// </summary>
        public static string CZ {
            get {
                return ResourceManager.GetString("CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ألمانيا.
        /// </summary>
        public static string DE {
            get {
                return ResourceManager.GetString("DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دييغو غارسيا.
        /// </summary>
        public static string DG {
            get {
                return ResourceManager.GetString("DG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيبوتي.
        /// </summary>
        public static string DJ {
            get {
                return ResourceManager.GetString("DJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدانمرك.
        /// </summary>
        public static string DK {
            get {
                return ResourceManager.GetString("DK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دومينيكا.
        /// </summary>
        public static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمهورية الدومينيك.
        /// </summary>
        public static string DO {
            get {
                return ResourceManager.GetString("DO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجزائر.
        /// </summary>
        public static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيوتا وميليلا.
        /// </summary>
        public static string EA {
            get {
                return ResourceManager.GetString("EA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإكوادور.
        /// </summary>
        public static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أستونيا.
        /// </summary>
        public static string EE {
            get {
                return ResourceManager.GetString("EE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصر.
        /// </summary>
        public static string EG {
            get {
                return ResourceManager.GetString("EG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصحراء الغربية.
        /// </summary>
        public static string EH {
            get {
                return ResourceManager.GetString("EH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أريتريا.
        /// </summary>
        public static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إسبانيا.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إثيوبيا.
        /// </summary>
        public static string ET {
            get {
                return ResourceManager.GetString("ET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فنلندا.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيجي.
        /// </summary>
        public static string FJ {
            get {
                return ResourceManager.GetString("FJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر فوكلاند.
        /// </summary>
        public static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميكرونيزيا.
        /// </summary>
        public static string FM {
            get {
                return ResourceManager.GetString("FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر فارو.
        /// </summary>
        public static string FO {
            get {
                return ResourceManager.GetString("FO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرنسا.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجابون.
        /// </summary>
        public static string GA {
            get {
                return ResourceManager.GetString("GA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المملكة المتحدة.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غرينادا.
        /// </summary>
        public static string GD {
            get {
                return ResourceManager.GetString("GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جورجيا.
        /// </summary>
        public static string GE {
            get {
                return ResourceManager.GetString("GE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غويانا الفرنسية.
        /// </summary>
        public static string GF {
            get {
                return ResourceManager.GetString("GF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غيرنزي.
        /// </summary>
        public static string GG {
            get {
                return ResourceManager.GetString("GG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غانا.
        /// </summary>
        public static string GH {
            get {
                return ResourceManager.GetString("GH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جبل طارق.
        /// </summary>
        public static string GI {
            get {
                return ResourceManager.GetString("GI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غرينلاند.
        /// </summary>
        public static string GL {
            get {
                return ResourceManager.GetString("GL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غامبيا.
        /// </summary>
        public static string GM {
            get {
                return ResourceManager.GetString("GM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غينيا.
        /// </summary>
        public static string GN {
            get {
                return ResourceManager.GetString("GN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جوادلوب.
        /// </summary>
        public static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غينيا الإستوائية.
        /// </summary>
        public static string GQ {
            get {
                return ResourceManager.GetString("GQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليونان.
        /// </summary>
        public static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جورجيا الجنوبية وجزر ساندويتش الجنوبية.
        /// </summary>
        public static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غواتيمالا.
        /// </summary>
        public static string GT {
            get {
                return ResourceManager.GetString("GT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غوام.
        /// </summary>
        public static string GU {
            get {
                return ResourceManager.GetString("GU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غينيا بيساو.
        /// </summary>
        public static string GW {
            get {
                return ResourceManager.GetString("GW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غيانا.
        /// </summary>
        public static string GY {
            get {
                return ResourceManager.GetString("GY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هونغ كونغ الصينية.
        /// </summary>
        public static string HK {
            get {
                return ResourceManager.GetString("HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هندوراس.
        /// </summary>
        public static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كرواتيا.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هايتي.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنغاريا.
        /// </summary>
        public static string HU {
            get {
                return ResourceManager.GetString("HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر الكناري.
        /// </summary>
        public static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أندونيسيا.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أيرلندا.
        /// </summary>
        public static string IE {
            get {
                return ResourceManager.GetString("IE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزيرة مان.
        /// </summary>
        public static string IM {
            get {
                return ResourceManager.GetString("IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهند.
        /// </summary>
        public static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإقليم البريطاني في المحيط الهندي.
        /// </summary>
        public static string IO {
            get {
                return ResourceManager.GetString("IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العراق.
        /// </summary>
        public static string IQ {
            get {
                return ResourceManager.GetString("IQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيران.
        /// </summary>
        public static string IR {
            get {
                return ResourceManager.GetString("IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أيسلندا.
        /// </summary>
        public static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إيطاليا.
        /// </summary>
        public static string IT {
            get {
                return ResourceManager.GetString("IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيرسي.
        /// </summary>
        public static string JE {
            get {
                return ResourceManager.GetString("JE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جامايكا.
        /// </summary>
        public static string JM {
            get {
                return ResourceManager.GetString("JM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأردن.
        /// </summary>
        public static string JO {
            get {
                return ResourceManager.GetString("JO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليابان.
        /// </summary>
        public static string JP {
            get {
                return ResourceManager.GetString("JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كينيا.
        /// </summary>
        public static string KE {
            get {
                return ResourceManager.GetString("KE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرغيزستان.
        /// </summary>
        public static string KG {
            get {
                return ResourceManager.GetString("KG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمبوديا.
        /// </summary>
        public static string KH {
            get {
                return ResourceManager.GetString("KH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كيريباتي.
        /// </summary>
        public static string KI {
            get {
                return ResourceManager.GetString("KI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر القمر.
        /// </summary>
        public static string KM {
            get {
                return ResourceManager.GetString("KM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت كيتس ونيفيس.
        /// </summary>
        public static string KN {
            get {
                return ResourceManager.GetString("KN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوريا الشمالية.
        /// </summary>
        public static string KP {
            get {
                return ResourceManager.GetString("KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوريا الجنوبية.
        /// </summary>
        public static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكويت.
        /// </summary>
        public static string KW {
            get {
                return ResourceManager.GetString("KW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر الكايمن.
        /// </summary>
        public static string KY {
            get {
                return ResourceManager.GetString("KY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كازاخستان.
        /// </summary>
        public static string KZ {
            get {
                return ResourceManager.GetString("KZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاوس.
        /// </summary>
        public static string LA {
            get {
                return ResourceManager.GetString("LA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لبنان.
        /// </summary>
        public static string LB {
            get {
                return ResourceManager.GetString("LB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت لوسيا.
        /// </summary>
        public static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليختنشتاين.
        /// </summary>
        public static string LI {
            get {
                return ResourceManager.GetString("LI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سريلانكا.
        /// </summary>
        public static string LK {
            get {
                return ResourceManager.GetString("LK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليبيريا.
        /// </summary>
        public static string LR {
            get {
                return ResourceManager.GetString("LR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليسوتو.
        /// </summary>
        public static string LS {
            get {
                return ResourceManager.GetString("LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليتوانيا.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوكسمبورغ.
        /// </summary>
        public static string LU {
            get {
                return ResourceManager.GetString("LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاتفيا.
        /// </summary>
        public static string LV {
            get {
                return ResourceManager.GetString("LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليبيا.
        /// </summary>
        public static string LY {
            get {
                return ResourceManager.GetString("LY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المغرب.
        /// </summary>
        public static string MA {
            get {
                return ResourceManager.GetString("MA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موناكو.
        /// </summary>
        public static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مولدافيا.
        /// </summary>
        public static string MD {
            get {
                return ResourceManager.GetString("MD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجبل الأسود.
        /// </summary>
        public static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت مارتن.
        /// </summary>
        public static string MF {
            get {
                return ResourceManager.GetString("MF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدغشقر.
        /// </summary>
        public static string MG {
            get {
                return ResourceManager.GetString("MG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر المارشال.
        /// </summary>
        public static string MH {
            get {
                return ResourceManager.GetString("MH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدونيا.
        /// </summary>
        public static string MK {
            get {
                return ResourceManager.GetString("MK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالي.
        /// </summary>
        public static string ML {
            get {
                return ResourceManager.GetString("ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ميانمار -بورما.
        /// </summary>
        public static string MM {
            get {
                return ResourceManager.GetString("MM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منغوليا.
        /// </summary>
        public static string MN {
            get {
                return ResourceManager.GetString("MN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكاو الصينية (منطقة إدارية خاصة).
        /// </summary>
        public static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر ماريانا الشمالية.
        /// </summary>
        public static string MP {
            get {
                return ResourceManager.GetString("MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارتينيك.
        /// </summary>
        public static string MQ {
            get {
                return ResourceManager.GetString("MQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موريتانيا.
        /// </summary>
        public static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مونتسرات.
        /// </summary>
        public static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مالطا.
        /// </summary>
        public static string MT {
            get {
                return ResourceManager.GetString("MT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موريشيوس.
        /// </summary>
        public static string MU {
            get {
                return ResourceManager.GetString("MU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر المالديف.
        /// </summary>
        public static string MV {
            get {
                return ResourceManager.GetString("MV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاوي.
        /// </summary>
        public static string MW {
            get {
                return ResourceManager.GetString("MW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكسيك.
        /// </summary>
        public static string MX {
            get {
                return ResourceManager.GetString("MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماليزيا.
        /// </summary>
        public static string MY {
            get {
                return ResourceManager.GetString("MY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موزمبيق.
        /// </summary>
        public static string MZ {
            get {
                return ResourceManager.GetString("MZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناميبيا.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاليدونيا الجديدة.
        /// </summary>
        public static string NC {
            get {
                return ResourceManager.GetString("NC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النيجر.
        /// </summary>
        public static string NE {
            get {
                return ResourceManager.GetString("NE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزيرة نورفوك.
        /// </summary>
        public static string NF {
            get {
                return ResourceManager.GetString("NF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيجيريا.
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيكاراغوا.
        /// </summary>
        public static string NI {
            get {
                return ResourceManager.GetString("NI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هولندا.
        /// </summary>
        public static string NL {
            get {
                return ResourceManager.GetString("NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النرويج.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيبال.
        /// </summary>
        public static string NP {
            get {
                return ResourceManager.GetString("NP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناورو.
        /// </summary>
        public static string NR {
            get {
                return ResourceManager.GetString("NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيوي.
        /// </summary>
        public static string NU {
            get {
                return ResourceManager.GetString("NU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نيوزيلاندا.
        /// </summary>
        public static string NZ {
            get {
                return ResourceManager.GetString("NZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عُمان.
        /// </summary>
        public static string OM {
            get {
                return ResourceManager.GetString("OM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بنما.
        /// </summary>
        public static string PA {
            get {
                return ResourceManager.GetString("PA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيرو.
        /// </summary>
        public static string PE {
            get {
                return ResourceManager.GetString("PE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بولينيزيا الفرنسية.
        /// </summary>
        public static string PF {
            get {
                return ResourceManager.GetString("PF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بابوا غينيا الجديدة.
        /// </summary>
        public static string PG {
            get {
                return ResourceManager.GetString("PG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفلبين.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باكستان.
        /// </summary>
        public static string PK {
            get {
                return ResourceManager.GetString("PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بولندا.
        /// </summary>
        public static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت بيير وميكولون.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر بيتكيرن.
        /// </summary>
        public static string PN {
            get {
                return ResourceManager.GetString("PN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بورتوريكو.
        /// </summary>
        public static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأراضي الفلسطينية.
        /// </summary>
        public static string PS {
            get {
                return ResourceManager.GetString("PS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البرتغال.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالاو.
        /// </summary>
        public static string PW {
            get {
                return ResourceManager.GetString("PW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باراغواي.
        /// </summary>
        public static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قطر.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روينيون.
        /// </summary>
        public static string RE {
            get {
                return ResourceManager.GetString("RE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رومانيا.
        /// </summary>
        public static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صربيا.
        /// </summary>
        public static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روسيا.
        /// </summary>
        public static string RU {
            get {
                return ResourceManager.GetString("RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رواندا.
        /// </summary>
        public static string RW {
            get {
                return ResourceManager.GetString("RW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المملكة العربية السعودية.
        /// </summary>
        public static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر سليمان.
        /// </summary>
        public static string SB {
            get {
                return ResourceManager.GetString("SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيشل.
        /// </summary>
        public static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السودان.
        /// </summary>
        public static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السويد.
        /// </summary>
        public static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنغافورة.
        /// </summary>
        public static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت هيلنا.
        /// </summary>
        public static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلوفينيا.
        /// </summary>
        public static string SI {
            get {
                return ResourceManager.GetString("SI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفالبارد وجان مايان.
        /// </summary>
        public static string SJ {
            get {
                return ResourceManager.GetString("SJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلوفاكيا.
        /// </summary>
        public static string SK {
            get {
                return ResourceManager.GetString("SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيراليون.
        /// </summary>
        public static string SL {
            get {
                return ResourceManager.GetString("SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سان مارينو.
        /// </summary>
        public static string SM {
            get {
                return ResourceManager.GetString("SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنغال.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصومال.
        /// </summary>
        public static string SO {
            get {
                return ResourceManager.GetString("SO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سورينام.
        /// </summary>
        public static string SR {
            get {
                return ResourceManager.GetString("SR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنوب السودان.
        /// </summary>
        public static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساو تومي وبرينسيبي.
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السلفادور.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سينت مارتن.
        /// </summary>
        public static string SX {
            get {
                return ResourceManager.GetString("SX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوريا.
        /// </summary>
        public static string SY {
            get {
                return ResourceManager.GetString("SY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوازيلاند.
        /// </summary>
        public static string SZ {
            get {
                return ResourceManager.GetString("SZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تريستان دي كونها.
        /// </summary>
        public static string TA {
            get {
                return ResourceManager.GetString("TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر الترك وجايكوس.
        /// </summary>
        public static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشاد.
        /// </summary>
        public static string TD {
            get {
                return ResourceManager.GetString("TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المقاطعات الجنوبية الفرنسية.
        /// </summary>
        public static string TF {
            get {
                return ResourceManager.GetString("TF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجو.
        /// </summary>
        public static string TG {
            get {
                return ResourceManager.GetString("TG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تايلاند.
        /// </summary>
        public static string TH {
            get {
                return ResourceManager.GetString("TH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طاجكستان.
        /// </summary>
        public static string TJ {
            get {
                return ResourceManager.GetString("TJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توكيلو.
        /// </summary>
        public static string TK {
            get {
                return ResourceManager.GetString("TK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تيمور الشرقية.
        /// </summary>
        public static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تركمانستان.
        /// </summary>
        public static string TM {
            get {
                return ResourceManager.GetString("TM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تونس.
        /// </summary>
        public static string TN {
            get {
                return ResourceManager.GetString("TN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تونغا.
        /// </summary>
        public static string TO {
            get {
                return ResourceManager.GetString("TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تركيا.
        /// </summary>
        public static string TR {
            get {
                return ResourceManager.GetString("TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترينيداد وتوباغو.
        /// </summary>
        public static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توفالو.
        /// </summary>
        public static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تايوان.
        /// </summary>
        public static string TW {
            get {
                return ResourceManager.GetString("TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تانزانيا.
        /// </summary>
        public static string TZ {
            get {
                return ResourceManager.GetString("TZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوكرانيا.
        /// </summary>
        public static string UA {
            get {
                return ResourceManager.GetString("UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوغندا.
        /// </summary>
        public static string UG {
            get {
                return ResourceManager.GetString("UG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر الولايات المتحدة النائية.
        /// </summary>
        public static string UM {
            get {
                return ResourceManager.GetString("UM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الولايات المتحدة.
        /// </summary>
        public static string US {
            get {
                return ResourceManager.GetString("US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أورغواي.
        /// </summary>
        public static string UY {
            get {
                return ResourceManager.GetString("UY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوزبكستان.
        /// </summary>
        public static string UZ {
            get {
                return ResourceManager.GetString("UZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفاتيكان.
        /// </summary>
        public static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سانت فنسنت وغرنادين.
        /// </summary>
        public static string VC {
            get {
                return ResourceManager.GetString("VC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فنزويلا.
        /// </summary>
        public static string VE {
            get {
                return ResourceManager.GetString("VE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر فرجين البريطانية.
        /// </summary>
        public static string VG {
            get {
                return ResourceManager.GetString("VG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر فرجين الأمريكية.
        /// </summary>
        public static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فيتنام.
        /// </summary>
        public static string VN {
            get {
                return ResourceManager.GetString("VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فانواتو.
        /// </summary>
        public static string VU {
            get {
                return ResourceManager.GetString("VU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزر والس وفوتونا.
        /// </summary>
        public static string WF {
            get {
                return ResourceManager.GetString("WF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساموا.
        /// </summary>
        public static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كوسوفو.
        /// </summary>
        public static string XK {
            get {
                return ResourceManager.GetString("XK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليمن.
        /// </summary>
        public static string YE {
            get {
                return ResourceManager.GetString("YE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مايوت.
        /// </summary>
        public static string YT {
            get {
                return ResourceManager.GetString("YT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنوب أفريقيا.
        /// </summary>
        public static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زامبيا.
        /// </summary>
        public static string ZM {
            get {
                return ResourceManager.GetString("ZM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زيمبابوي.
        /// </summary>
        public static string ZW {
            get {
                return ResourceManager.GetString("ZW", resourceCulture);
            }
        }
    }
}
