//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.AdamResurces {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _UserInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _UserInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.AdamResurces._UserInfo", typeof(_UserInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل متأكد من حذف هذا الموظف؟.
        /// </summary>
        public static string Are_you_sure__You_want_to_delete_this__ {
            get {
                return ResourceManager.GetString("Are you sure? You want to delete this.?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الميلاد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الإتصال.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البلد.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الزبائن.
        /// </summary>
        public static string CustomerList {
            get {
                return ResourceManager.GetString("CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف التعليق.
        /// </summary>
        public static string DeleteComment {
            get {
                return ResourceManager.GetString("DeleteComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف زبون.
        /// </summary>
        public static string DeleteCustomer {
            get {
                return ResourceManager.GetString("DeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف الموظف.
        /// </summary>
        public static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل بيانات الزبون.
        /// </summary>
        public static string DetailCustomer {
            get {
                return ResourceManager.GetString("DetailCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل بيانات الموظف.
        /// </summary>
        public static string DetailEmployee {
            get {
                return ResourceManager.GetString("DetailEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإيميل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة الموظفين.
        /// </summary>
        public static string EmployeeList {
            get {
                return ResourceManager.GetString("EmployeeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات عامة.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  الموقع.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الخروج.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الشخصية.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality1 {
            get {
                return ResourceManager.GetString("Nationality1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة زبون  .
        /// </summary>
        public static string NewCustomer {
            get {
                return ResourceManager.GetString("NewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة موظف.
        /// </summary>
        public static string NewEmployee {
            get {
                return ResourceManager.GetString("NewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبايل.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغير كلمة السر.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المدينة.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الدولة.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الزبون.
        /// </summary>
        public static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر حالة المهمة.
        /// </summary>
        public static string SelectDevelopment {
            get {
                return ResourceManager.GetString("SelectDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أختر الموظف.
        /// </summary>
        public static string SelectEmployee {
            get {
                return ResourceManager.GetString("SelectEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الجنس.
        /// </summary>
        public static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر الجنسية.
        /// </summary>
        public static string SelectNationality {
            get {
                return ResourceManager.GetString("SelectNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المستوى.
        /// </summary>
        public static string SelectPriority {
            get {
                return ResourceManager.GetString("SelectPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر المشروع.
        /// </summary>
        public static string SelectProject {
            get {
                return ResourceManager.GetString("SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث بيانات الزبون.
        /// </summary>
        public static string UpdateCustomer {
            get {
                return ResourceManager.GetString("UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث بيانات الموظف.
        /// </summary>
        public static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
    }
}
